# Generated by Django 5.0.14 on 2025-08-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0002_alter_assignment_grade_alter_assignment_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
