# Generated by Django 5.0.14 on 2025-08-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="is_onboarded",
            field=models.BooleanField(default=False),
        ),
    ]
