# Generated by Django 5.0.14 on 2025-08-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_studentprofile_is_onboarded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="parent",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="parent_contact",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="Parent/Guardian Phone"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="parent_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Parent/Guardian Name"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="photo",
            field=models.ImageField(
                default="", upload_to="profile_photos/", verbose_name="Profile Photo"
            ),
            preserve_default=False,
        ),
    ]
