# Generated by Django 5.0.14 on 2025-09-01 10:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_studentprofile_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminprofile",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="parentprofile",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
