# Generated by Django 5.0.14 on 2025-09-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_alter_adminprofile_photo_alter_parentprofile_photo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="admission_number",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
