# Generated by Django 5.0.4 on 2025-07-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_verification_token_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
