# Generated by Django 5.0.14 on 2025-09-25 11:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_studentprofile_admission_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
