# Generated by Django 5.0.14 on 2025-10-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="target_parents",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="announcement",
            name="target_students",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="announcement",
            name="target_teachers",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="AnnouncementAudience",
        ),
    ]
