# Generated by Django 5.2.4 on 2025-07-17 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classes",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="accounts.teacher",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="assigned_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="academics.classes",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="accounts.teacher",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="academics.subject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("name", "assigned_class")},
        ),
    ]
